name: Simple Fruit Inventory Management  # Optional workflow name

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Lint Python files with Pycodestyle
        run: |
          pycodestyle .  # Run pycodestyle to lint the code
          
      - name: Run tests with unittest
        run: |
          python -m unittest discover > result.log; tail -n 10 result.log  # Save the test results to result.log

      - name: Upload test results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: result.log  # Path to the file you want to upload as an artifact
